import os
import sys
import time
import runpod

# API-Key sicher über die Umgebungsvariablen einlesen
API_KEY = os.environ.get("RUNPOD_API_KEY")

if not API_KEY:
    print("❌ Fehler: Die Umgebungsvariable 'RUNPOD_API_KEY' wurde nicht gefunden.")
        print("Bitte setze sie im Terminal mit: export RUNPOD_API_KEY='dein_schlüssel'")
            sys.exit()

            runpod.api_key = API_KEY

            # Definition der 9 maßgeschneiderten Kreativ- und Chat-Setups
            SETUPS = {
                "1": {
                        "name": "Bildgenerierung (Forge / Stable Diffusion XL & FLUX)",
                                "gpu": "NVIDIA RTX 4090",
                                        "template": "runpod-stable-diffusion-forge",
                                                "port": 7860, "disk": 60
                                                    },
                                                        "2": {
                                                                "name": "Cinematic Video AI (ComfyUI - Wan2.2 / Hunyuan / Mochi)",
                                                                        "gpu": "NVIDIA RTX 4090",
                                                                                "template": "runpod-comfyui",
                                                                                        "port": 8188, "disk": 100
                                                                                            },
                                                                                                "3": {
                                                                                                        "name": "Social-Media Video & Schnitt (Echtzeit-Clips via LTX)",
                                                                                                                "gpu": "NVIDIA RTX 3090",
                                                                                                                        "template": "runpod-ltx-video",
                                                                                                                                "port": 8188, "disk": 70
                                                                                                                                    },
                                                                                                                                        "4": {
                                                                                                                                                "name": "Radio Jingles & Musikproduktion (AudioCraft / MusicGen / Bark)",
                                                                                                                                                        "gpu": "NVIDIA RTX 3090",
                                                                                                                                                                "template": "audiocraft-musicgen", 
                                                                                                                                                                        "port": 7860, "disk": 60
                                                                                                                                                                            },
                                                                                                                                                                                "5": {
                                                                                                                                                                                        "name": "Sprachsynthese & Gesangs-Klonierung (Voice-Cloning / TTS)",
                                                                                                                                                                                                "gpu": "NVIDIA RTX 3090",
                                                                                                                                                                                                        "template": "text-generation-webui", # Basis für AllTalk und XTTS-v2 Pipelines
                                                                                                                                                                                                                "port": 7860, "disk": 50
                                                                                                                                                                                                                    },
                                                                                                                                                                                                                        "6": {
                                                                                                                                                                                                                                "name": "Automatisierte Präsentations-Erstellung (Presenton / PPT-Agent)",
                                                                                                                                                                                                                                        "gpu": "NVIDIA RTX 3090",
                                                                                                                                                                                                                                                "template": "runpod-ollama",
                                                                                                                                                                                                                                                        "port": 11434, "disk": 50
                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                "7": {
                                                                                                                                                                                                                                                                        "name": "Interaktiver Text-Chat (DeepSeek-R1 / Llama-3 ohne Einschränkungen)",
                                                                                                                                                                                                                                                                                "gpu": "NVIDIA RTX 3090", # 24GB VRAM reichen perfekt für mächtige Textmodelle
                                                                                                                                                                                                                                                                                        "template": "text-generation-webui",
                                                                                                                                                                                                                                                                                                "port": 7860, "disk": 70
                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                        "8": {
                                                                                                                                                                                                                                                                                                                "name": "3D-Modellierung (Text-to-3D Objekt-Synthese via TripoSR)",
                                                                                                                                                                                                                                                                                                                        "gpu": "NVIDIA RTX 4090",
                                                                                                                                                                                                                                                                                                                                "template": "runpod-comfyui",
                                                                                                                                                                                                                                                                                                                                        "port": 8188, "disk": 70
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                "9": {
                                                                                                                                                                                                                                                                                                                                                        "name": "Video-Übersetzung & Lippensynchronisation (Lokale Open-Source-Alternative)",
                                                                                                                                                                                                                                                                                                                                                                "gpu": "NVIDIA RTX 3090", # Genug Power für Audio- und Lippenüberlagerungen (Wav2Lip)
                                                                                                                                                                                                                                                                                                                                                                        "template": "runpod-video-translator", 
                                                                                                                                                                                                                                                                                                                                                                                "port": 7860, "disk": 80
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                    def zeige_menue():
                                                                                                                                                                                                                                                                                                                                                                                        print("================================================================")
                                                                                                                                                                                                                                                                                                                                                                                            print("             Ultimate Creative Cloud Infrastructure             ")
                                                                                                                                                                                                                                                                                                                                                                                                print("================================================================")
                                                                                                                                                                                                                                                                                                                                                                                                    print("Bitte wähle das gewünschte Produktions-Profil:")
                                                                                                                                                                                                                                                                                                                                                                                                        print(" Bildgenerierung (Fokus: Fotorealismus & Design)")
                                                                                                                                                                                                                                                                                                                                                                                                            print(" Cinematic Video AI (High-End Physik & Kamera-Flüge)")
                                                                                                                                                                                                                                                                                                                                                                                                                print(" Social-Media Video & Schnitt (Schnelle Frame-Generierung)")
                                                                                                                                                                                                                                                                                                                                                                                                                    print(" Radio Jingles & Musikproduktion (Synthese & Gesang)")
                                                                                                                                                                                                                                                                                                                                                                                                                        print(" Sprachsynthese & Gesangs-Klonierung (Voice Cloning / TTS)")
                                                                                                                                                                                                                                                                                                                                                                                                                            print(" Automatisierte Präsentations-Erstellung (PPTX & Dokumente)")
                                                                                                                                                                                                                                                                                                                                                                                                                                print(" Interaktiver Text-Chat (Freies Brainstorming & Dialoge)")
                                                                                                                                                                                                                                                                                                                                                                                                                                    print(" 3D-Modellierung (Text-to-3D Objekt-Generierung)")
                                                                                                                                                                                                                                                                                                                                                                                                                                        print(" Video-Übersetzung & Lippensynchronisation (LipSync Hub)")
                                                                                                                                                                                                                                                                                                                                                                                                                                            print(" [Q] Beenden")
                                                                                                                                                                                                                                                                                                                                                                                                                                                print("----------------------------------------------------------------")

                                                                                                                                                                                                                                                                                                                                                                                                                                                def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                    zeige_menue()
                                                                                                                                                                                                                                                                                                                                                                                                                                                        auswahl = input("Auswahl eingeben (1-9 / Q): ").strip()

                                                                                                                                                                                                                                                                                                                                                                                                                                                            if auswahl.upper() == 'Q':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Vorgang abgebrochen.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sys.exit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if auswahl not in SETUPS:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("❌ Ungültige Auswahl. Bitte starte das Skript erneut.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sys.exit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    config = SETUPS[auswahl]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\n----------------------------------------------------------------")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"🔄 Lade Profil: {config['name']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"🖥️ Allokiere Hardware-Ressourcen: {config['gpu']}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("🚀 Initialisiere Cloud-Instanz...")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # volume_size=0 sorgt dafür, dass keine Standby-Fixkosten anfallen
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pod = runpod.create_pod(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name=f"Creative-Suite-Profile-{auswahl}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gpu_type_id=config['gpu'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                template_id=config['template'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            container_disk_size=config['disk'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        volume_size=0, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"\n❌ Fehler bei der Cloud-Bereitstellung: {e}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("Hinweis: Überprüfe die Server-Verfügbarkeit im gewählten Tarif.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sys.exit()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pod_id = pod["id"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"✅ Instanz erfolgreich gestartet! (ID: {pod_id})")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("⏳ Warte auf Netzwerk-Zuweisung und Anwendungs-Boot (ca. 1-2 Minuten)...")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            web_url = None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while True:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pod_info = runpod.get_pod(pod_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if pod_info.get("runtime"):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ports = pod_info["runtime"].get("ports", [])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        web_url = next((p["url"] for p in ports if p["privatePort"] == config['port']), None)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if web_url:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\n🎉 DIE INSTANZ IST BETRIEBSBEREIT!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"🔗 Link zur Benutzeroberfläche: {web_url}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        time.sleep(10)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(".", end="", flush=True)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n----------------------------------------------------------------")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print("Die Arbeitsumgebung ist im Browser geöffnet.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("⚠️  WICHTIG: Das Schließen des Fensters beendet nicht die Abrechnung!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input("\n👉 DRÜCKE HIER DIE ENTER-TASTE, UM DIE INSTANZ RESTLOS ZU LÖSCHEN (STOPPT KOSTEN) 👈")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n🛑 Fahre Server herunter und beende die Abrechnung...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        runpod.terminate_pod(pod_id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("💀 Instanz erfolgreich gelöscht. Es fallen keine weiteren Gebühren an.")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                